global_frame: map
track_unknown_space: true
rolling_window: true
map_type: costmap
static_map: false

plugins:
  - {name: obstacles_laser,         type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
