frequency: 30
delay: 3
zero_altitude: false
magnetic_declination_radians: 0.0043
yaw_offset: 1.57  # fixed by myahrs
broadcast_utm_transform: false
publish_filtered_gps: false
use_odometry_yaw: false
use_manual_datum: false
wait_for_datum: false
# datum: [1.35012856, 103.687695, 0.0, map, base_link]

