global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   resolution: 0.3
   transform_tolerance: 5.0
   map_type: costmap
