map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom
sensor_timeout: 0.5
two_d_mode: true

frequency: 20

odom0: odometry/vel
odom0_config: [false, false, false,
               false, false, false,
               true, false, false,
               false, false, true,
               false, false, false]
odom0_differential: false # with GPS, must be false
odom0_queue_size: 10

imu0: imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
              # true, true, true]
imu0_differential: false # with GPS, must be false
imu0_queue_size: 10
imu0_nodelay: 10
imu0_remove_gravitational_acceleration: true


print_diagnostics: true
